// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200404223124_AddRenter")]
    partial class AddRenter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Renter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("rContactMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("rCreate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("rEnable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("rExpire")
                        .HasColumnType("datetime2");

                    b.Property<string>("rName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rSub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Renters");
                });
#pragma warning restore 612, 618
        }
    }
}
